# Generated by Django 5.2.6 on 2025-09-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكورس')),
                ('description', models.TextField(verbose_name='المحتوى')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='صورة')),
            ],
        ),
    ]
