# Generated by Django 5.2.6 on 2025-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_duration_course_language_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('متقدم', 'متقدم')], max_length=50, null=True),
        ),
    ]
